services:
  # db:
  #   image: postgres:17.6
  #   #user:  ${USEROS}:${USEROS}
  #   container_name: fsoapp-db
  #   restart: always
  #   # set shared memory limit when using docker-compose
  #   shm_size: 128mb
  #   # or set shared memory limit when deploy via swarm stack
  #   networks:
  #       - fsoapp_network
  #   ports:
  #       - 5432:5432
  #   volumes:
  #       - ./data:/var/lib/postgresql/data
  #   env_file:
  #       - .env
  #   #environment:
  #   #  POSTGRES_USER: ${POSTGRES_USER}
  #   #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   #  PGDATA: ${PGDATA}

  fso.app:
    # image: ${DOCKER_REGISTRY-}fsoapp
    image: imageonfsoapp
    # build:
    #   context: .
    #   dockerfile: FSO.App/Dockerfile
    container_name: fsoapp-web    
    restart: always
    networks:
      - fsoapp_network
    ports:
      - 8080:8080    
    # env_file:
    #   - .env
    #environment:
    #  ASPNETCORE_ENVIRONMENT: Development
    #  ConnectionString: Host=${POSTGRES_HOST};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    #  ConnectionString: ${ConnectionString}
    #depends_on:
    #  - db  
    
    # Run this to accept the dev cert on windows "dotnet dev-certs https dotnet --trust"


networks:
  fsoapp_network:
    driver: bridge
    external: true