# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: FSO.App CI/CD

on:
  workflow_dispatch:  
  push:
    branches: [ "main" ]
 
jobs:
  build:
    name: FsoMVC project setup and build 
    runs-on: ubuntu-latest
    concurrency:
      group: solution_project_setup
      cancel-in-progress: true

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore Capstone.sln
    - name: Build
      run: dotnet build FsoMVC/ --no-restore
    - name: Test
      run: dotnet test FsoMVC/ --no-build --verbosity normal
    # - name: Publish
    #   run: dotnet publish --no-build --no-restore --os linux --arch x64 FSO.App/ -t:PublishContainer -p ContainerRegistry=docker.io 
  
  push_to_registry:
    name: Build and push the docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
      attestations: write
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_USERNAME }}/fso-app

      - name: Log in to your Docker Hub account
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.KONTO_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: FSO.App
          file: FSO.App/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

